name: ci

on:
  push:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: elghetani
          password: AbdLwhap123

      - name: build and naming from docker file
        run: docker build -t elghetani/elghetani:1.0 .

      - name: push to docker hub
        run: docker push elghetani/elghetani:1.0