name: ci

on:
  push:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: elghetani
          password: AbdLwhap123
   